sudo: true
language: php
dist: trusty

env:
  global:
    - CC_TEST_REPORTER_ID=d572a6fcb618ca97b91c06fb4e11ad1b0a0ba817eead5c233c46234e45f96105

addons:
  code_climate:
    repo_token:
      secure: d572a6fcb618ca97b91c06fb4e11ad1b0a0ba817eead5c233c46234e45f96105

php:
  - 7.2

services:
  - redis-server
  - postgres

cache:
  directories:
    - vendor

before_script:
   - psql -c 'create database testing;' -U postgres
   - export DISPLAY=:99.0
   - sh -e /etc/init.d/xvfb start
   - ./vendor/laravel/dusk/bin/chromedriver-linux &
   - cp .env.travis .env
   - php artisan serve &

script:
  - php artisan dusk

install:
   - travis_retry composer install --no-interaction --prefer-dist --no-suggest

   - cp .env.travis .env
   - cp phpunit.travis.xml phpunit.xml

   - php artisan key:generate

after_script:
  - vendor/bin/test-reporter

after_success:
  - chmod +x ./tests.sh; ./tests.sh