sudo: true

dist: trusty

language: php

env:
  global:
    - CC_TEST_REPORTER_ID=d572a6fcb618ca97b91c06fb4e11ad1b0a0ba817eead5c233c46234e45f96105

addons:
  chrome: stable

  code_climate:
    repo_token:
      secure: d572a6fcb618ca97b91c06fb4e11ad1b0a0ba817eead5c233c46234e45f96105

php:
  - 7.2

services:
  - redis-server
  - postgres

before_script:
   - psql -c 'create database testing;' -U postgres
   - cp .env.travis .env
   - cp phpunit.travis.xml phpunit.xml

    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
    - php artisan serve &

install:
   - travis_retry composer install --no-interaction --prefer-dist --no-suggest

   - cp .env.travis .env
   - cp phpunit.travis.xml phpunit.xml

   - php artisan key:generate

script:
  - phpunit
  - php artisan dusk

after_script:
  - vendor/bin/test-reporter

after_success:
  - chmod +x ./tests.sh; ./tests.sh



